### ISSUE TITLE
Removing item from shopping cart on cart page redirects 302 to homepage 

### ISSUE THREAD

**Issue by qsolutions-pl** [ho-nl/magento2-ReachDigital_StoreResolver#19]
Hi guys!

Module is **great** and thanks for sharing but we've noticed a small bug and trying to work out a fix ourselves (no luck yet).

### Setup
1. Magento 2.3.x
2. Multistore setup enabled
3. No plugins for URLs  / redirects

### How to replicate the issue?
1. add item to cart
2. go to cart page
3. click  "remove from cart" button

### Expected result
1. users stays on the cart page and item is removed

### Actual result:
1. user is being redirected to the homepage
2. same thing is happening for all ajax actions (like adding to cart from 3rd party extensions)

**Comment by paales** [comment]
@JeroenVanLeusden / @joeriLock93 Does that ring a bell?
