### ISSUE TITLE
Submit to packagist

### ISSUE THREAD

**Issue by danslo** [ho-nl/magento2-ReachDigital_StoreResolver#21]
I tried following the instructions:
```
composer require reach-digital/magento2-storeresolver
```

But this module has not been submitted to packagist, so it will fail unless you add an entry to `repositories`.

**Comment by PascalBrouwers** [comment]
Let's fixed that right now

**Comment by PascalBrouwers** [comment]
https://packagist.org/packages/reach-digital/magento2-storeresolver

**Comment by danslo** [comment]
🙌
